# Generated by Django 5.0.9 on 2026-04-27 18:44

from django.db import migrations, models
import os

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SociosCPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('data_ultimo_update', models.DateTimeField(auto_now=True)),
                ('col1', models.CharField(max_length=100)),
                ('col2', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'SociosCPF',
                'verbose_name_plural': 'SociosCPF',
                'db_table': os.getenv('TB_CLIENTE'),
            },
        ),
    ]
