# Generated by Django 5.0.9 on 2026-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioscpf',
            name='col1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='socioscpf',
            name='col2',
            field=models.CharField(max_length=10),
        ),
    ]
